service: appimeals-backend

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-2

functions:
  users:
    handler: users.handler
    events:
      - http: 
          path: user-registration
          method: get
          cors: true
      - http: 
          path: user-registration
          method: post
          cors: true

  favourites:
    handler: favourites.handler
    events:
      - http: 
          path: favourites
          method: get
          cors: true
      - http: 
          path: favourites
          method: post
          cors: true
      - http: 
          path: favourites
          method: delete
          cors: true

  mealPreferences:
    handler: mealPreferences.handler
    events:
      - http: 
          path: mealPreferences
          method: get
          cors: true
      - http: 
          path: mealPreferences
          method: post
          cors: true
      - http: 
          path: mealPreferences
          method: put
          cors: true

  mealSelections:
    handler: mealSelections.handler
    events:
      - http: 
          path: mealSelections
          method: get
          cors: true
      - http: 
          path: mealSelections
          method: post
          cors: true
      - http: 
          path: mealSelections
          method: put
          cors: true

  recipes:
    handler: recipes.handler
    events:
      - http:
          path: browse-recipes
          method: get
          cors: true   
