# Cross-Stack References in Serverless
# https://serverless-stack.com/chapters/cross-stack-references-in-serverless.html
# "...Now let’s look at how to work with multiple services in your Serverless application."

service: appimeals-backend

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-2


functions:
  users:
    handler: users.handler
    events:
      - http: 
          path: users
          method: get
          cors: true
      - http: 
          path: users
          method: post
          cors: true
  # favourites:
  #   handler: favourites/favourites.handler
  #   events:
  #     - http:
  #       path: favourites
  #       method: get
  #       cors: true
  #     - http:
  #       path: favourites
  #       method: post
  #       cors: true
  #     - http:
  #       path: favourites
  #       method: delete
  #       cors: true
  # mealPreferences:
  #   handler: mealPreferences/mealPreferences.handler
  #   events:
  #     - http:
  #       path: mealPreferences
  #       method: post
  #       cors: true
  #     - http:
  #       path: mealPreferences
  #       method: get
  #       cors: true
  #     - http:
  #       path: mealPreferences
  #       method: put
  #       cors: true
  # mealSelections:
  #   handler: mealSelections/mealSelections.handler
  #   events:
  #     - http:
  #       path: mealSelections
  #       method: post
  #       cors: true
  #     - http:
  #       path: mealSelections
  #       method: get
  #       cors: true
  #     - http:
  #       path: mealSelections
  #       method: put
  #       cors: true
  # recipes:
  #   handler: recipes/recipes.handler
  #   events:
  #     - http:
  #         path: browse-recipes
  #         method: get
  #         cors: true
  #     - http:
  #         path: browse-recipes/{recipeId}
  #         method: delete
  #         cors: true
  #     - http:
  #         path: browse-recipes
  #         method: post
  #         cors: true
  #     - http:
  #         path: browse-recipes/{recipeId}
  #         method: put
  #         cors: true
