service: appimeals-backend

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-2

functions:
  users:
    handler: users.handler
    environment:
        DB_HOST: ${opt:DB_HOST}
        DB_USER: ${opt:DB_USER}
        DB_PASSWORD: ${opt:DB_PASSWORD}
    events:
      - http: 
          path: users
          method: get
          cors: true
      - http: 
          path: users
          method: post
          cors: true

  favourites:
    handler: favourites.handler
    environment:
        DB_HOST: ${opt:DB_HOST}
        DB_USER: ${opt:DB_USER}
        DB_PASSWORD: ${opt:DB_PASSWORD}
    events:
      - http: 
          path: favourites
          method: get
          cors: true
      - http: 
          path: favourites
          method: post
          cors: true
      - http: 
          path: favourites
          method: delete
          cors: true

  mealPreferences:
    handler: mealPreferences.handler
    environment:
        DB_HOST: ${opt:DB_HOST}
        DB_USER: ${opt:DB_USER}
        DB_PASSWORD: ${opt:DB_PASSWORD}
    events:
      - http: 
          path: mealPreferences
          method: get
          cors: true
      - http: 
          path: mealPreferences
          method: post
          cors: true
      - http: 
          path: mealPreferences
          method: put
          cors: true

  recipes:
    handler: recipes.handler
    environment:
        DB_HOST: ${opt:DB_HOST}
        DB_USER: ${opt:DB_USER}
        DB_PASSWORD: ${opt:DB_PASSWORD}
    events:
      - http:
          path: browse-recipes
          method: get
          cors: true
      - http:
          path: browse-recipes
          method: post
          cors: true

  mealChoices:
    handler: mealChoices.handler
    environment:
        DB_HOST: ${opt:DB_HOST}
        DB_USER: ${opt:DB_USER}
        DB_PASSWORD: ${opt:DB_PASSWORD}
    events:
      - http:
          path: MyMealChoices
          method: get
          cors: true
      - http:
           path: MyMealChoices
           method: delete
           cors: true
   
    
          
